### ISSUE TITLE
Upgrade to SublimeText3

### ISSUE THREAD

**Issue by fluke** [Kentzo/SublimeMagick#2]
This is an excellent tool would love to see it in SublimeText3.

**Comment by Kentzo** [comment]
Noted.

**Comment by fluke** [comment]
Thanks. Looking forward to it.

**Comment by Kentzo** [comment]
@kartikluke https://github.com/Kentzo/SublimeMagick/pull/3

**Comment by fluke** [comment]
Sweet. Will get it immediately.
